mybatis-plus:
  mapper-locations: classpath*:org/cly/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat

logging:
  level:
    root: info
    org.cly: debug
  path: logs/
  file: film.log

